services:
  # PostgreSQL service
  postgres:
    image: postgres:16
    container_name: postgres-db
    environment:
      POSTGRES_USER: dbadmin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
